### ISSUE TITLE
Travis Build Ruby 2.1, Puppet 4.5

### ISSUE THREAD

**Issue by martialblog** [vision-it/vision-ssh#1]
Facts need to be defined to ensure the rake spec test is running.

https://travis-ci.org/vision-it/vision-ssh/jobs/140015427
`error during compilation: Evaluation Error: Unknown variable: '::sshdsakey'. at `

**Comment by nce** [comment]
could be our ENV variable forcing [strict mode](https://docs.puppet.com/puppet/latest/reference/lang_variables.html#unassigned-variables-and-strict-mode). And [this](https://github.com/rodjek/rspec-puppet/issues/385) is probably why only the rspec tests  fail.

**Comment by martialblog** [comment]
Jup. It's strict mode.
spec_helper.rb > c.strict_variables = false # Doen't work because of ENV variable.

Possible solutions: 
STRICT_VARIABLES="no" in rspec tests.

Beaker gets tested with STRICT_VARIABLES="yes" anyways.

**Comment by martialblog** [comment]
Done and Done: 
https://github.com/vision-it/vision-ssh/commit/ddbe3bafddbc1a413328929c70038bbf43b9e863
